[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
ndarray = "0.15"
rand = "0.8"

pyo3 = "0.22.6"

zerogame = { path = "crates/zerogame" }

[profile.release]
lto = 'fat'
codegen-units = 1