game_settings:
  N: 6
  gate: 0.01
  layer: 0.
  MAX_STEPS: 13

mcts_settings:
  c_puct: 4
  epsilon: 0.7
  dirichlet_alpha: 0.7
  num_mcts_simulations: 100  # 探索回数を増加
  max_depth: 13      # 探索深さを増加

network_settings:
  n_blocks: 24
  filters: 256             # フィルタ数を増加
  use_bias: False
  use_se: True
  learning_rate: 0.0001

training_settings:
  num_cpus: 8
  num_gpus: 0
  n_episodes: 300
  buffer_size: 400          # リプレイバッファサイズを減少
  batch_size: 64
  epochs_per_update: 50
  update_period: 50
  save_period: 50
  eval_period: 50