[package]
name = "zerogame"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "zerogame"
doctest = false
crate-type = ["cdylib"]

[dependencies]
ndarray.workspace = true
rand = "0.8"

[dependencies.pyo3]
workspace = true
features = ["py-clone"]
